"""
Seed the database with the 12 built-in recipes from the original frontend.
Run once: python -c "from backend.seed import seed_recipes; seed_recipes()"
"""
import uuid
from backend.extensions import db
from backend.models.models import Recipe

SEED_RECIPES = [
    {
        "id": "smoky-tomato-pasta",
        "title": "Smoky tomato pasta with burrata",
        "category": "Mains",
        "author": "Priya Nair",
        "time": 35,
        "difficulty": "Easy",
        "servings": 4,
        "rating": 4.8,
        "reviews": 212,
        "image": "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=1200&q=80",
        "description": "A weeknight pasta built on a smoky, slow-blistered tomato sauce, finished with torn burrata so it melts into every bite.",
        "ingredients": [
            {"id": "i1", "amount": 400, "unit": "g", "name": "rigatoni or casarecce"},
            {"id": "i2", "amount": 3, "unit": None, "name": "tbsp olive oil"},
            {"id": "i3", "amount": 6, "unit": None, "name": "garlic cloves, sliced"},
            {"id": "i4", "amount": 1, "unit": None, "name": "tsp smoked paprika"},
            {"id": "i5", "amount": 800, "unit": "g", "name": "canned whole tomatoes"},
            {"id": "i6", "amount": 1, "unit": "tsp", "name": "chili flakes"},
            {"id": "i7", "amount": 1, "unit": None, "name": "ball burrata"},
            {"id": "i8", "amount": 1, "unit": None, "name": "handful basil leaves"},
        ],
        "steps": [
            "Bring a large pot of salted water to a boil and cook pasta until just shy of al dente.",
            "Warm the olive oil over medium heat and gently cook the garlic until fragrant but not browned, about 1 minute.",
            "Stir in the smoked paprika and chili flakes, then add the tomatoes, crushing them with the back of a spoon.",
            "Simmer uncovered for 15 minutes, stirring occasionally, until the sauce thickens and deepens in color.",
            "Toss the drained pasta through the sauce with a splash of pasta water until glossy.",
            "Plate and tear the burrata over the top. Finish with basil, a crack of pepper, and more olive oil.",
        ],
        "tags": ["comfort food", "vegetarian", "weeknight"],
    },
    {
        "id": "miso-butter-salmon",
        "title": "Miso butter salmon with charred greens",
        "category": "Mains",
        "author": "Daniel Cho",
        "time": 25,
        "difficulty": "Easy",
        "servings": 2,
        "rating": 4.9,
        "reviews": 341,
        "image": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1200&q=80",
        "description": "Salty, nutty miso butter glazes the salmon as it roasts, while broccolini gets a hard char alongside it. One pan, twenty five minutes, done.",
        "ingredients": [
            {"id": "i1", "amount": 2, "unit": None, "name": "salmon fillets"},
            {"id": "i2", "amount": 2, "unit": "tbsp", "name": "white miso paste"},
            {"id": "i3", "amount": 2, "unit": "tbsp", "name": "unsalted butter, softened"},
            {"id": "i4", "amount": 1, "unit": "tbsp", "name": "honey"},
            {"id": "i5", "amount": 1, "unit": None, "name": "bunch broccolini"},
            {"id": "i6", "amount": 1, "unit": None, "name": "lime, cut into wedges"},
            {"id": "i7", "amount": 1, "unit": "tsp", "name": "sesame seeds"},
        ],
        "steps": [
            "Heat the oven to 220C / 425F and line a sheet pan.",
            "Mash together the miso, butter, and honey until smooth.",
            "Toss the broccolini with a little oil and salt and spread on the pan.",
            "Nestle the salmon among the greens and spread the miso butter generously over each fillet.",
            "Roast for 12 to 14 minutes until the salmon flakes and the greens are charred at the edges.",
            "Finish with sesame seeds and a squeeze of lime.",
        ],
        "tags": ["seafood", "gluten-free", "weeknight"],
    },
    {
        "id": "sourdough-morning-buns",
        "title": "Cardamom morning buns",
        "category": "Breakfast",
        "author": "Elena Marsh",
        "time": 150,
        "difficulty": "Involved",
        "servings": 12,
        "rating": 4.7,
        "reviews": 98,
        "image": "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=1200&q=80",
        "description": "Laminated dough, a brown sugar cardamom filling, and a sugared crust. These take a slow Sunday morning, and every minute is worth it.",
        "ingredients": [
            {"id": "i1", "amount": 500, "unit": "g", "name": "all-purpose flour"},
            {"id": "i2", "amount": 227, "unit": "g", "name": "cold unsalted butter"},
            {"id": "i3", "amount": 120, "unit": "g", "name": "brown sugar"},
            {"id": "i4", "amount": 2, "unit": "tsp", "name": "ground cardamom"},
            {"id": "i5", "amount": 7, "unit": "g", "name": "instant yeast"},
            {"id": "i6", "amount": 240, "unit": "ml", "name": "whole milk, warm"},
            {"id": "i7", "amount": 100, "unit": "g", "name": "granulated sugar, for rolling"},
        ],
        "steps": [
            "Make an enriched dough with the flour, yeast, milk, and a portion of the butter, then chill for 1 hour.",
            "Laminate the dough by folding in cold butter in three turns, chilling between each.",
            "Roll the dough into a large rectangle and spread with brown sugar and cardamom.",
            "Roll tightly into a log, slice into rounds, and press each into a sugared muffin tin.",
            "Proof for 45 minutes until puffy, then bake at 190C / 375F for 22 to 25 minutes.",
            "Turn out onto a tray of sugar while still warm and roll to coat.",
        ],
        "tags": ["baking", "weekend project", "vegetarian"],
    },
    {
        "id": "shakshuka",
        "title": "Green shakshuka with feta",
        "category": "Breakfast",
        "author": "Priya Nair",
        "time": 30,
        "difficulty": "Easy",
        "servings": 3,
        "rating": 4.6,
        "reviews": 154,
        "image": "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=1200&q=80",
        "description": "A herby, spinach-and-leek base instead of the usual tomato, with eggs poached right in the pan and salty feta crumbled on top.",
        "ingredients": [
            {"id": "i1", "amount": 2, "unit": "tbsp", "name": "olive oil"},
            {"id": "i2", "amount": 1, "unit": None, "name": "leek, sliced"},
            {"id": "i3", "amount": 200, "unit": "g", "name": "spinach"},
            {"id": "i4", "amount": 1, "unit": None, "name": "bunch cilantro"},
            {"id": "i5", "amount": 4, "unit": None, "name": "large eggs"},
            {"id": "i6", "amount": 80, "unit": "g", "name": "feta, crumbled"},
            {"id": "i7", "amount": 0.5, "unit": "tsp", "name": "cumin"},
        ],
        "steps": [
            "Cook the leek in olive oil over medium heat until soft, about 6 minutes.",
            "Add the spinach in batches and wilt down completely.",
            "Blend half the mixture with cilantro and cumin, then stir it back into the pan.",
            "Make four wells in the greens and crack in the eggs.",
            "Cover and cook for 5 to 6 minutes until whites are set and yolks still soft.",
            "Scatter feta over the top and serve straight from the pan.",
        ],
        "tags": ["vegetarian", "gluten-free", "weeknight"],
    },
    {
        "id": "french-onion-soup",
        "title": "Slow french onion soup",
        "category": "Soups",
        "author": "Marcus Webb",
        "time": 120,
        "difficulty": "Involved",
        "servings": 4,
        "rating": 4.9,
        "reviews": 267,
        "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&q=80",
        "description": "Onions caramelized low and slow for two hours until they taste almost sweet, deglazed with wine, and topped with a broiled gruyere crust.",
        "ingredients": [
            {"id": "i1", "amount": 1.5, "unit": "kg", "name": "yellow onions, thinly sliced"},
            {"id": "i2", "amount": 4, "unit": "tbsp", "name": "butter"},
            {"id": "i3", "amount": 240, "unit": "ml", "name": "dry white wine"},
            {"id": "i4", "amount": 1.5, "unit": "l", "name": "beef stock"},
            {"id": "i5", "amount": 1, "unit": None, "name": "baguette, sliced"},
            {"id": "i6", "amount": 200, "unit": "g", "name": "gruyere, grated"},
            {"id": "i7", "amount": 2, "unit": None, "name": "thyme sprigs"},
        ],
        "steps": [
            "Melt the butter and cook the onions over low heat, stirring occasionally, for 90 minutes until deeply caramelized.",
            "Deglaze the pot with white wine, scraping up any browned bits.",
            "Add the stock and thyme and simmer for 20 minutes.",
            "Toast the baguette slices until crisp.",
            "Ladle soup into oven-safe bowls, top with toast and a heap of gruyere.",
            "Broil until the cheese is bubbling and browned in spots.",
        ],
        "tags": ["comfort food", "weekend project"],
    },
    {
        "id": "roasted-carrot-soup",
        "title": "Roasted carrot and ginger soup",
        "category": "Soups",
        "author": "Elena Marsh",
        "time": 50,
        "difficulty": "Easy",
        "servings": 4,
        "rating": 4.5,
        "reviews": 88,
        "image": "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=1200&q=80",
        "description": "Sweet roasted carrots, warming ginger, and a swirl of coconut milk. Blended completely smooth and best with crusty bread.",
        "ingredients": [
            {"id": "i1", "amount": 900, "unit": "g", "name": "carrots, chopped"},
            {"id": "i2", "amount": 1, "unit": None, "name": "onion, quartered"},
            {"id": "i3", "amount": 30, "unit": "g", "name": "fresh ginger, sliced"},
            {"id": "i4", "amount": 800, "unit": "ml", "name": "vegetable stock"},
            {"id": "i5", "amount": 200, "unit": "ml", "name": "coconut milk"},
            {"id": "i6", "amount": 2, "unit": "tbsp", "name": "olive oil"},
        ],
        "steps": [
            "Toss carrots, onion, and ginger with olive oil and roast at 200C / 400F for 30 minutes.",
            "Transfer to a pot with the stock and simmer for 10 minutes.",
            "Blend until completely smooth, adding water to loosen if needed.",
            "Stir in most of the coconut milk, reserving some for serving.",
            "Season to taste with salt and a squeeze of lemon.",
            "Serve with a swirl of coconut milk and cracked pepper.",
        ],
        "tags": ["vegan", "gluten-free", "weeknight"],
    },
    {
        "id": "charred-corn-salad",
        "title": "Charred corn and avocado salad",
        "category": "Salads",
        "author": "Daniel Cho",
        "time": 20,
        "difficulty": "Easy",
        "servings": 4,
        "rating": 4.4,
        "reviews": 76,
        "image": "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=1200&q=80",
        "description": "Sweet corn charred hard in a dry skillet, tossed with avocado, lime, and cotija. Ten minutes of effort for a lot of flavor.",
        "ingredients": [
            {"id": "i1", "amount": 4, "unit": None, "name": "ears corn, kernels removed"},
            {"id": "i2", "amount": 2, "unit": None, "name": "avocados, diced"},
            {"id": "i3", "amount": 0.5, "unit": None, "name": "red onion, finely diced"},
            {"id": "i4", "amount": 2, "unit": None, "name": "limes, juiced"},
            {"id": "i5", "amount": 60, "unit": "g", "name": "cotija, crumbled"},
            {"id": "i6", "amount": 1, "unit": None, "name": "jalapeno, minced"},
        ],
        "steps": [
            "Heat a dry skillet until very hot and char the corn kernels, stirring occasionally, about 6 minutes.",
            "Let the corn cool slightly, then combine with avocado, onion, and jalapeno.",
            "Dress with lime juice and a pinch of salt.",
            "Top with crumbled cotija just before serving.",
        ],
        "tags": ["vegetarian", "gluten-free", "no-cook option"],
    },
    {
        "id": "citrus-fennel-salad",
        "title": "Winter citrus and fennel salad",
        "category": "Salads",
        "author": "Marcus Webb",
        "time": 15,
        "difficulty": "Easy",
        "servings": 4,
        "rating": 4.6,
        "reviews": 61,
        "image": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1200&q=80",
        "description": "Shaved fennel, blood orange, and mint with a sharp olive oil dressing. Bright enough to cut through any heavy winter meal.",
        "ingredients": [
            {"id": "i1", "amount": 2, "unit": None, "name": "fennel bulbs, shaved"},
            {"id": "i2", "amount": 3, "unit": None, "name": "blood oranges, segmented"},
            {"id": "i3", "amount": 1, "unit": None, "name": "handful mint leaves"},
            {"id": "i4", "amount": 40, "unit": "g", "name": "pecorino, shaved"},
            {"id": "i5", "amount": 3, "unit": "tbsp", "name": "olive oil"},
            {"id": "i6", "amount": 1, "unit": "tbsp", "name": "red wine vinegar"},
        ],
        "steps": [
            "Shave the fennel as thin as possible, ideally on a mandoline.",
            "Arrange fennel and orange segments on a platter.",
            "Whisk the olive oil and vinegar with a pinch of salt.",
            "Drizzle the dressing over the salad and scatter with mint and pecorino.",
        ],
        "tags": ["vegetarian", "gluten-free", "no-cook"],
    },
    {
        "id": "brown-butter-cookies",
        "title": "Brown butter chocolate chip cookies",
        "category": "Desserts",
        "author": "Elena Marsh",
        "time": 45,
        "difficulty": "Easy",
        "servings": 18,
        "rating": 5.0,
        "reviews": 402,
        "image": "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=1200&q=80",
        "description": "Nutty brown butter, dark brown sugar, and two kinds of chocolate. Crisp edges, chewy centers, the only cookie recipe you need.",
        "ingredients": [
            {"id": "i1", "amount": 226, "unit": "g", "name": "unsalted butter"},
            {"id": "i2", "amount": 200, "unit": "g", "name": "dark brown sugar"},
            {"id": "i3", "amount": 100, "unit": "g", "name": "granulated sugar"},
            {"id": "i4", "amount": 2, "unit": None, "name": "large eggs"},
            {"id": "i5", "amount": 320, "unit": "g", "name": "all-purpose flour"},
            {"id": "i6", "amount": 250, "unit": "g", "name": "chocolate chips, mixed dark and milk"},
            {"id": "i7", "amount": 1, "unit": "tsp", "name": "flaky salt"},
        ],
        "steps": [
            "Brown the butter in a light-colored pan until nutty and amber, then cool slightly.",
            "Whisk the browned butter with both sugars until glossy.",
            "Beat in the eggs one at a time.",
            "Fold in the flour, baking soda, and salt until just combined, then fold in the chocolate.",
            "Chill the dough for at least 30 minutes.",
            "Scoop onto trays and bake at 190C / 375F for 11 to 13 minutes. Finish with flaky salt.",
        ],
        "tags": ["baking", "vegetarian", "crowd-pleaser"],
    },
    {
        "id": "lemon-olive-oil-cake",
        "title": "Lemon olive oil cake",
        "category": "Desserts",
        "author": "Priya Nair",
        "time": 70,
        "difficulty": "Easy",
        "servings": 10,
        "rating": 4.8,
        "reviews": 189,
        "image": "https://images.unsplash.com/photo-1519869325930-281384150729?w=1200&q=80",
        "description": "A moist, fine-crumbed cake that stays fresh for days. Good olive oil and a lot of lemon zest do all the work.",
        "ingredients": [
            {"id": "i1", "amount": 280, "unit": "g", "name": "all-purpose flour"},
            {"id": "i2", "amount": 300, "unit": "g", "name": "granulated sugar"},
            {"id": "i3", "amount": 240, "unit": "ml", "name": "extra virgin olive oil"},
            {"id": "i4", "amount": 3, "unit": None, "name": "large eggs"},
            {"id": "i5", "amount": 240, "unit": "ml", "name": "whole milk"},
            {"id": "i6", "amount": 3, "unit": None, "name": "lemons, zested and juiced"},
        ],
        "steps": [
            "Heat the oven to 175C / 350F and grease a bundt or loaf pan.",
            "Whisk the sugar and lemon zest together until fragrant.",
            "Whisk in the eggs, then the olive oil, milk, and lemon juice.",
            "Fold in the flour, baking powder, and a pinch of salt until just combined.",
            "Pour into the pan and bake for 45 to 50 minutes until a skewer comes out clean.",
            "Cool completely before turning out and glazing if desired.",
        ],
        "tags": ["baking", "vegetarian"],
    },
    {
        "id": "ginger-lime-mocktail",
        "title": "Ginger lime spritz",
        "category": "Drinks",
        "author": "Marcus Webb",
        "time": 10,
        "difficulty": "Easy",
        "servings": 2,
        "rating": 4.3,
        "reviews": 44,
        "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200&q=80",
        "description": "Fresh ginger syrup, lots of lime, and a hard top of soda water. Sharp, not too sweet, and ready in ten minutes.",
        "ingredients": [
            {"id": "i1", "amount": 60, "unit": "ml", "name": "fresh ginger syrup"},
            {"id": "i2", "amount": 40, "unit": "ml", "name": "lime juice"},
            {"id": "i3", "amount": 240, "unit": "ml", "name": "soda water"},
            {"id": "i4", "amount": 1, "unit": None, "name": "lime, sliced, for garnish"},
            {"id": "i5", "amount": 1, "unit": None, "name": "handful mint, for garnish"},
        ],
        "steps": [
            "Fill two glasses with ice.",
            "Divide the ginger syrup and lime juice between the glasses.",
            "Top with soda water and stir gently.",
            "Garnish with lime slices and mint.",
        ],
        "tags": ["vegan", "gluten-free", "no-cook"],
    },
    {
        "id": "spiced-chai-latte",
        "title": "Slow-steeped spiced chai",
        "category": "Drinks",
        "author": "Daniel Cho",
        "time": 20,
        "difficulty": "Easy",
        "servings": 4,
        "rating": 4.7,
        "reviews": 133,
        "image": "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=1200&q=80",
        "description": "Whole spices simmered low and slow with black tea, then finished with steamed milk. Better than anything from a syrup bottle.",
        "ingredients": [
            {"id": "i1", "amount": 6, "unit": None, "name": "green cardamom pods, crushed"},
            {"id": "i2", "amount": 1, "unit": None, "name": "cinnamon stick"},
            {"id": "i3", "amount": 4, "unit": None, "name": "cloves"},
            {"id": "i4", "amount": 4, "unit": "tsp", "name": "black tea leaves"},
            {"id": "i5", "amount": 500, "unit": "ml", "name": "water"},
            {"id": "i6", "amount": 500, "unit": "ml", "name": "whole milk"},
            {"id": "i7", "amount": 3, "unit": "tbsp", "name": "sugar, or to taste"},
        ],
        "steps": [
            "Simmer the whole spices in water for 10 minutes to build a strong base.",
            "Add the tea leaves and steep for 3 minutes.",
            "Pour in the milk and sugar and bring to a gentle simmer.",
            "Strain into cups and serve hot.",
        ],
        "tags": ["vegetarian", "gluten-free", "weekend project"],
    },
]


def seed_recipes():
    """Insert built-in recipes if they don't already exist."""
    for data in SEED_RECIPES:
        if db.session.get(Recipe, data["id"]):
            continue
        r = Recipe(
            id=data["id"],
            title=data["title"],
            category=data["category"],
            description=data["description"],
            image=data["image"],
            time=data["time"],
            servings=data["servings"],
            difficulty=data["difficulty"],
            rating=data["rating"],
            reviews=data["reviews"],
            is_default=True,
            author_name=data["author"],
        )
        r.ingredients = data["ingredients"]
        r.steps = data["steps"]
        r.tags = data["tags"]
        db.session.add(r)
    db.session.commit()